title: At-Tawahidiyya
description: La ilaha illa Allah. The Logical Restoration of Divine Oneness.
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal

# IMPORTANT: Add these two lines
url: "https://tawhidi-suleyman.github.io"
baseurl: "/Al-Tawhidiyya"

permalink: /:categories/:title/

collections:
  foundations:
    output: true
  tafsir:
    output: true
  refutations:
    output: true
